// Mock data for development based on SACCO spec
import type {
  Member,
  Account,
  Transaction,
  LoanProduct,
  LoanApplication,
  DashboardKPI,
  User,
} from "@/types";

export const LOAN_PRODUCTS: LoanProduct[] = [
  {
    code: "L-EDU",
    name: "Education Loan",
    interest_rate: 12.5,
    interest_type: "FLAT",
    min_term_months: 6,
    max_term_months: 24,
    penalty_rate: 2.0,
    category: "Service",
  },
  {
    code: "L-MED",
    name: "Medical Loan",
    interest_rate: 12.5,
    interest_type: "FLAT",
    min_term_months: 6,
    max_term_months: 24,
    penalty_rate: 2.0,
    category: "Service",
  },
  {
    code: "L-SOC",
    name: "Social Event Loan",
    interest_rate: 12.5,
    interest_type: "FLAT",
    min_term_months: 6,
    max_term_months: 24,
    penalty_rate: 2.0,
    category: "Service",
  },
  {
    code: "L-HSE",
    name: "Home Construction",
    interest_rate: 17.0,
    interest_type: "FLAT",
    min_term_months: 12,
    max_term_months: 120,
    penalty_rate: 2.5,
    category: "Asset",
  },
  {
    code: "L-VEH",
    name: "Vehicle Purchase",
    interest_rate: 14.0,
    interest_type: "FLAT",
    min_term_months: 12,
    max_term_months: 60,
    penalty_rate: 2.0,
    category: "Asset",
  },
  {
    code: "L-BIZ",
    name: "Business Expansion",
    interest_rate: 14.0,
    interest_type: "DECLINING",
    min_term_months: 12,
    max_term_months: 60,
    penalty_rate: 2.0,
    category: "Business",
  },
  {
    code: "L-AGR",
    name: "Urban Agriculture",
    interest_rate: 14.0,
    interest_type: "DECLINING",
    min_term_months: 12,
    max_term_months: 60,
    penalty_rate: 2.0,
    category: "Business",
  },
  {
    code: "L-INS",
    name: "Insurance Loan",
    interest_rate: 12.5,
    interest_type: "FLAT",
    min_term_months: 6,
    max_term_months: 12,
    penalty_rate: 1.5,
    category: "Special",
  },
];

export const MOCK_USERS: User[] = [
  {
    user_id: "u1",
    full_name: "Abebe Kebede",
    email: "abebe.k@alefdelta.et",
    role: "TELLER",
    branch: "Arada Branch",
    active: true,
  },
  {
    user_id: "u2",
    full_name: "Tigist Haile",
    email: "tigist.h@alefdelta.et",
    role: "CREDIT_OFFICER",
    branch: "Arada Branch",
    active: true,
  },
  {
    user_id: "u3",
    full_name: "Solomon Tesfaye",
    email: "solomon.t@alefdelta.et",
    role: "MANAGER",
    branch: "Arada Branch",
    active: true,
  },
  {
    user_id: "u4",
    full_name: "Hanna Alemu",
    email: "hanna.a@alefdelta.et",
    role: "ADMIN",
    active: true,
  },
];

export const MOCK_MEMBERS: Member[] = [
  {
    member_id: "m1",
    membership_no: "AD-2023-0001",
    first_name: "Yonas",
    middle_name: "Tadesse",
    last_name: "Mekonen",
    phone_primary: "+251911234567",
    email: "yonas.t@email.com",
    gender: "M",
    marital_status: "MARRIED",
    address_subcity: "Arada",
    address_woreda: "Woreda 05",
    address_house_no: "H-123",
    member_type: "GOV_EMP",
    monthly_income: 25000,
    status: "ACTIVE",
    registered_date: "2023-01-15T00:00:00Z",
  },
  {
    member_id: "m2",
    membership_no: "AD-2023-0002",
    first_name: "Marta",
    middle_name: "Alemayehu",
    last_name: "Worku",
    phone_primary: "+251922345678",
    email: "marta.a@email.com",
    gender: "F",
    marital_status: "SINGLE",
    address_subcity: "Kirkos",
    address_woreda: "Woreda 02",
    address_house_no: "H-456",
    member_type: "TRADER",
    monthly_income: 35000,
    tin_number: "TIN-123456789",
    status: "ACTIVE",
    registered_date: "2023-02-20T00:00:00Z",
  },
  {
    member_id: "m3",
    membership_no: "AD-2023-0003",
    first_name: "Dawit",
    middle_name: "Bekele",
    last_name: "Girma",
    phone_primary: "+251933456789",
    gender: "M",
    marital_status: "MARRIED",
    address_subcity: "Bole",
    address_woreda: "Woreda 08",
    address_house_no: "H-789",
    member_type: "NGO",
    monthly_income: 28000,
    status: "ACTIVE",
    registered_date: "2023-03-10T00:00:00Z",
  },
];

export const MOCK_ACCOUNTS: Account[] = [
  {
    account_id: "acc1",
    member_id: "m1",
    product_code: "SAV_COMPULSORY",
    balance: 45000,
    lien_amount: 15000,
    currency: "ETB",
    status: "ACTIVE",
    version: 1,
    created_at: "2023-01-15T00:00:00Z",
  },
  {
    account_id: "acc2",
    member_id: "m1",
    product_code: "SAV_VOLUNTARY",
    balance: 120000,
    lien_amount: 0,
    currency: "ETB",
    status: "ACTIVE",
    version: 1,
    created_at: "2023-01-15T00:00:00Z",
  },
  {
    account_id: "acc3",
    member_id: "m2",
    product_code: "SAV_COMPULSORY",
    balance: 65000,
    lien_amount: 25000,
    currency: "ETB",
    status: "ACTIVE",
    version: 1,
    created_at: "2023-02-20T00:00:00Z",
  },
];

export const MOCK_TRANSACTIONS: Transaction[] = [
  {
    txn_id: "txn1",
    account_id: "acc1",
    txn_type: "DEPOSIT",
    amount: 5000,
    balance_after: 45000,
    reference: "SAL-2024-001",
    performed_by: "u1",
    created_at: "2024-11-01T10:00:00Z",
    idempotency_key: "idem-001",
  },
  {
    txn_id: "txn2",
    account_id: "acc1",
    txn_type: "WITHDRAWAL",
    amount: 2000,
    balance_after: 43000,
    reference: "WD-2024-001",
    performed_by: "u1",
    created_at: "2024-11-05T14:30:00Z",
    idempotency_key: "idem-002",
  },
  {
    txn_id: "txn3",
    account_id: "acc2",
    txn_type: "DEPOSIT",
    amount: 10000,
    balance_after: 120000,
    reference: "CASH-2024-001",
    performed_by: "u1",
    created_at: "2024-11-10T09:15:00Z",
    idempotency_key: "idem-003",
  },
];

export const MOCK_LOAN_APPLICATIONS: LoanApplication[] = [
  {
    loan_id: "loan1",
    member_id: "m1",
    product_code: "L-EDU",
    applied_amount: 50000,
    approved_amount: 50000,
    term_months: 24,
    interest_rate: 12.5,
    purpose_description: "University tuition fees for child",
    repayment_frequency: "MONTHLY",
    workflow_status: "APPROVED",
    disbursement_date: "2024-10-01",
    next_payment_date: "2024-12-01",
    created_at: "2024-09-15T00:00:00Z",
    updated_at: "2024-09-20T00:00:00Z",
  },
  {
    loan_id: "loan2",
    member_id: "m2",
    product_code: "L-BIZ",
    applied_amount: 100000,
    approved_amount: 0,
    term_months: 36,
    interest_rate: 14.0,
    purpose_description: "Expansion of retail business",
    repayment_frequency: "MONTHLY",
    workflow_status: "REVIEW",
    created_at: "2024-11-05T00:00:00Z",
    updated_at: "2024-11-05T00:00:00Z",
  },
  {
    loan_id: "loan3",
    member_id: "m3",
    product_code: "L-VEH",
    applied_amount: 300000,
    approved_amount: 0,
    term_months: 48,
    interest_rate: 14.0,
    purpose_description: "Purchase of commercial vehicle",
    repayment_frequency: "MONTHLY",
    workflow_status: "SUBMITTED",
    created_at: "2024-11-18T00:00:00Z",
    updated_at: "2024-11-18T00:00:00Z",
  },
];

export const MOCK_DASHBOARD_KPI: DashboardKPI = {
  total_savings: 4567890.5,
  total_loans_outstanding: 2345678.0,
  monthly_deposits: 567890.25,
  delinquency_rate: 3.2,
  active_members: 1234,
  pending_approvals: 12,
};
